name: Atraleo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15398
title: "Atraleo Let's Plays "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2d2d'
    - '#c1222e'
    - '#717171'
    - '#afafaf'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
