name: Atraleo
favicon: null
layout_spectrum: 0.37968
typography_spectrum: 0.15398
title: "Atraleo | Let's Play"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77341925-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2d2d'
    - '#c1222e'
    - '#717171'
    - '#afafaf'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
