name: Atraleo
favicon: null
layout_spectrum: 0.1444995643105358
typography_spectrum: 0.2635527066886425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8427351440768689
  lightness: 0.4522367403842509
  saturation: 0.8437582168262452
  rhythmicContrast: 0.9369075582362711
purpose: []
